#                           Hub Plus
#                          Version 0.5
#                       By Connor Linfoot
# Please read the documentation available at the link below!
# http://dev.bukkit.org/bukkit-plugins/hub-plus/
Config Version: 2

Protected Worlds: world
Hub World: world
Clear Inventory On Join: false
Clock Cooldown: 3
On Join Broadcast: Welcome <playername> to the server!
On Quit Broadcast: <playername> left the server!
Hub On Join: true
Send Stats: true
Broadcast Prefix: "[HubPlus]"
Custom Hub Command: lobby
Disable Plugins Command: false
Firework Cooldown: 15
Launch Pads: enabled
Launch Pads Bottom Block: Redstone Block
Launch Pads Top Block: Stone Plate

Clans Enabled: false
Clan Member Limit: 8
Clan Starting Points: 100

Friends Enabled: false
Friends Limit: 0


Database Host: localhost
Database User: user
Database Pass: pass
Database Name: name

Blood Enabled: false
Blood Worlds: all
Blood Entitys:
  All: true
  Bat: false
  Blaze: false
  Cave Spider: false
  Chicken: false
  Cow: false
  Creeper: false
  Enderman: false
  Ghast: false
  Giant: false
  Horse: false
  Iron Golem: false
  Magma Cube: false
  Mushroom Cow: false
  Ocelot: false
  Pig: false
  Player: false
  Sheep: false
  Silverfish: false
  Skeleton: false
  Slime: false
  Snowman: false
  Spider: false
  Squid: false
  Villager: false
  Witch: false
  Wither: false
  Wolf: false
  Zombie: false
  Zombie Pigman: false

DO NOT EDIT: DO NOT EDIT BELOW THIS LINE!
COMMENT1: Below is config for compass! Ignore this its for the future!
Compass Rows: 4
PlayersHiding: