#                           Hub Plus
#                          Version 0.5
#                       By Connor Linfoot
# Please read the documentation available at the link below!
# http://dev.bukkit.org/bukkit-plugins/hub-plus/
Config Version: 3

Protected Worlds:
- world
Hub World: world

Broadcasts Enabled: true
On Join Broadcast: Welcome <playername> to the server!
On Quit Broadcast: <playername> left the server!

Hub On Join: true
Send Stats: true
Broadcast Prefix: "[HubPlus]"
Custom Hub Command: lobby
Disable Plugins Command: false
Firework Cooldown: 15

Hide Players Enabled: true
Hide Players Item: watch
Hide Players Cooldown: 3
Clear Inventory On Join: false

Launch Pads Enabled: true
Launch Pads Bottom Block: Redstone Block
Launch Pads Top Block: Stone Plate
Launch Pad Speed: 5


Clans Enabled: false
Clan Member Limit: 8
Clan Starting Points: 100

Friends Enabled: false
Friends Limit: 0

Chat Sensor: replace

Database Host: localhost
Database User: user
Database Pass: pass
Database Name: name
Database Port: 3306

DO NOT EDIT: DO NOT EDIT BELOW THIS LINE!
COMMENT1: Below is config for compass! Ignore this its for the future!
Compass Rows: 4
PlayersHiding: