name: Hub Plus
description: Hub Plus is a simple and yet very large Hub plugin. It has multiple features including clans, friends and more!
main: com.connorlinfoot.hubplus.HubPlus
version: 0.5
commands:
  hubplus:
    description: HubPlus Main Command
  hp:
    description: HubPlus Main Command
  world:
    description: Get the world name
  hub:
    description: Go to hub
  broadcast:
    description: Send out a broadcast to the server
  bc:
    description: Send out a broadcast to the server
  fw:
    description: Firework
  clan:
    description: Clan command
  fly:
    description: Fly command
  heal:
    description: Heal command
  friend:
    description: Friend command
  gmc:
    description: Creative Mode command
  gms:
    description: Survival Mode command
  gma:
    description: Adventure Mode command
  c:
    description: Clan command
  f:
    description: Friend command
permissions:
  hubplus.hub:
    description: Allow users to use /hub command
    default: true
  hubplus.admin:
    description: Allow users to use /hubplus and other future admin commands
    default: op
  hubplus.protection.bypass:
    description: Bypass block protection in hub world
    default: op
  hubplus.inv.bypass:
    description: Bypass any inv limits, such as moving items or dropping in hub world
    default: op
  hubplus.jointp.bypass:
    description: Bypass the TP to hub upon joining the server
    default: op
  hubplus.broadcast:
    description: Required to use /broadcast or /bc command
    default: op
  hubplus.sign.create:
    description: Required to be able to create a Hub sign
    default: op
  hubplus.sign.use:
    description: Required to be able to use a hub sign
    default: true
  hubplus.firework:
    description: Access to /fw command
    default: op
  hubplus.fly.self:
    description: Access to /fly command
    default: op
  hubplus.heal.self:
    description: Access to /heal command
    default: op
  hubplus.fw:
    description: Access to /fw command
    default: op
  hubplus.clan:
    description: Access to /clan command
    default: op
  hubplus.clan.info:
    description: Access to /clan info command
    default: op
  hubplus.clan.info.other:
    description: Access to /clan info <clan name> command
    default: op
  hubplus.clan.create:
    description: Access to /clan create command
    default: op
  hubplus.clan.join:
    description: Access to /clan join command
    default: op
  hubplus.ride:
    description: Allow a player to right click another player to ride
    default: op
  hubplus.gamemode.creative:
    description: Access to /gmc command
    default: op
  hubplus.gamemode.survival:
    description: Access to /gms command
    default: op
  hubplus.gamemode.adventure:
    description: Access to /gma command
    default: op